export default {
  UNKNOWN_USER_ENTER_EMAIL: 'UNKNOWN_USER_ENTER_EMAIL',
  EXISTING_USER_ENTER_PASSWORD: 'EXISTING_USER_ENTER_PASSWORD',
  NEW_USER_CREATE_ACCOUNT: 'NEW_USER_CREATE_ACCOUNT',
  EXISTING_USER_WITH_FACEBOOK_ACCOUNT: 'EXISTING_USER_WITH_FACEBOOK_ACCOUNT',
  EXISTING_USER_WITH_GOOGLE_ACCOUNT: 'EXISTING_USER_WITH_GOOGLE_ACCOUNT',
  SUBMIT_CREATE_ACCOUNT: 'SUBMIT_CREATE_ACCOUNT',
  SUBMIT_LOG_IN: 'SUBMIT_LOG_IN'
};
