name: Organizerify deploy (frontend)

on:
  push:
    branches:
      - master

jobs:
  build-and-release-frontend:
    name: Build packages and frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download dependencies
        run: yarn
      - name: Build all packages
        run: yarn build:packages
      - name: Build frontend
        run: yarn build:frontend
