name: Organizerify deploy (frontend)

on:
  push:
    paths:
      - '/**'

jobs:
  build:
    name: Build packages and frontend
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Checkout repository
        uses: actions/checkout@v2
